import { poppins } from "./fonts";

export enum COLORS {
  WHITE = "#ffffff",
  BLACK = "#000000",
  PRIMARY_NAVY = "#09090B",
  ACCENT_TAN = "#A1A1AA",
  NAVY_GRADIENT_START = "#18181B",
  NAVY_GRADIENT_END = "#09090B",
  GLASS_BG = "rgba(255, 255, 255, 0.8)",
  GLASS_BORDER = "rgba(0, 0, 0, 0.08)",
  TEXT_PRIMARY = "#18181B",
  TEXT_SECONDARY = "#71717A",
  INPUT_BG = "#F4F4F5",
  BG_LIGHT = "#FAFAFA",
  BG_GRADIENT_END = "#E4E4E7",
  SUCCESS = "#10B981",
  SUCCESS_DARK = "#059669",
  ERROR = "#EF4444",
  ERROR_DARK = "#DC2626",
  WARNING = "#F59E0B",
  WARNING_DARK = "#D97706",
  INFO = "#3B82F6",
  INFO_DARK = "#2563EB",
  INDIGO = "#4F46E5",
  SECONDARY_NAVY = "#27272A",
  PURPLE = "#7C3AED",
  TEAL = "#0D9488",
  BORDER_GRAY = "#E4E4E7",
  BORDER_LIGHT = "#D4D4D8",
  TRANSPARENT = "transparent",

  // Status Badge Colors
  STATUS_SUCCESS_BG = "rgba(16, 185, 129, 0.12)",
  STATUS_SUCCESS_TEXT = "#059669",
  STATUS_SUCCESS_BORDER = "rgba(16, 185, 129, 0.25)",

  STATUS_INFO_BG = "rgba(59, 130, 246, 0.12)",
  STATUS_INFO_TEXT = "#2563EB",
  STATUS_INFO_BORDER = "rgba(59, 130, 246, 0.25)",

  STATUS_PURPLE_BG = "rgba(124, 58, 237, 0.12)",
  STATUS_PURPLE_TEXT = "#7C3AED",
  STATUS_PURPLE_BORDER = "rgba(124, 58, 237, 0.25)",

  STATUS_ERROR_BG = "rgba(239, 68, 68, 0.12)",
  STATUS_ERROR_TEXT = "#DC2626",
  STATUS_ERROR_BORDER = "rgba(239, 68, 68, 0.25)",

  STATUS_WARNING_BG = "rgba(245, 158, 11, 0.12)",
  STATUS_WARNING_TEXT = "#D97706",
  STATUS_WARNING_BORDER = "rgba(245, 158, 11, 0.25)",

  STATUS_TEAL_BG = "rgba(13, 148, 136, 0.12)",
  STATUS_TEAL_TEXT = "#0D9488",
  STATUS_TEAL_BORDER = "rgba(13, 148, 136, 0.25)",

  STATUS_INDIGO_BG = "rgba(79, 70, 229, 0.12)",
  STATUS_INDIGO_TEXT = "#4F46E5",
  STATUS_INDIGO_BORDER = "rgba(79, 70, 229, 0.25)",

  // Translucent / Overlay Colors
  WHITE_ALPHA_20 = "rgba(255, 255, 255, 0.2)",
  WHITE_ALPHA_15 = "rgba(255, 255, 255, 0.15)",
  WHITE_ALPHA_75 = "rgba(255, 255, 255, 0.75)",
  WHITE_ALPHA_12 = "rgba(255, 255, 255, 0.12)",
  ERROR_LIGHT_BG = "rgba(239, 68, 68, 0.05)",
  ERROR_LIGHT_BORDER = "rgba(239, 68, 68, 0.15)",
  HOVER_BG = "rgba(0, 0, 0, 0.04)",
  HOVER_BG_LIGHT = "rgba(0, 0, 0, 0.015)",
}

export enum FONT_WEIGHT {
  LIGHT = 300,
  REGULAR = 400,
  MEDIUM = 500,
  SEMI_BOLD = 600,
  BOLD = 700,
}

export enum FONT_SIZE {
  PAGE_TITLE = "34px",
  SECTION_TITLE = "18px",
  SUB_HEADING = "16px",
  BODY = "14px",
  TABLE_HEADER = "13.5px",
  TABLE_CELL = "13.5px",
  TABLE_CELL_SECONDARY = "13px",
  CAPTION = "12px",
  BADGE = "11px",
  // Legacy mappings
  FS28 = "28px",
  FS18 = "18px",
  FS16 = "16px",
  FS14 = "14px",
  FS12 = "12px",
}

export const TYPOGRAPHY = {
  PAGE_TITLE: {
    fontFamily: poppins.style.fontFamily,
    fontSize: FONT_SIZE.PAGE_TITLE,
    fontWeight: FONT_WEIGHT.BOLD,
    color: COLORS.PRIMARY_NAVY,
    letterSpacing: "-0.5px",
  },
  SECTION_TITLE: {
    fontFamily: poppins.style.fontFamily,
    fontSize: FONT_SIZE.SECTION_TITLE,
    fontWeight: FONT_WEIGHT.BOLD,
    color: COLORS.PRIMARY_NAVY,
  },
  TABLE_HEADER: {
    fontFamily: poppins.style.fontFamily,
    fontSize: FONT_SIZE.TABLE_HEADER,
    fontWeight: FONT_WEIGHT.BOLD,
    color: COLORS.PRIMARY_NAVY,
    letterSpacing: "0.2px",
  },
  
  TABLE_CELL_PRIMARY: {
    fontFamily: poppins.style.fontFamily,
    fontSize: FONT_SIZE.TABLE_CELL,
    fontWeight: FONT_WEIGHT.SEMI_BOLD,
    color: COLORS.PRIMARY_NAVY,
  },
  TABLE_CELL_SECONDARY: {
    fontFamily: poppins.style.fontFamily,
    fontSize: FONT_SIZE.TABLE_CELL_SECONDARY,
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: COLORS.TEXT_SECONDARY,
  },

  BADGE: {
    fontFamily: poppins.style.fontFamily,
    fontSize: FONT_SIZE.CAPTION,
    fontWeight: FONT_WEIGHT.SEMI_BOLD,
  },
};

export enum USER_ROLES {
  SUPER_ADMIN = "SUPER_ADMIN",
  IAIRE_ADMIN = "IAIRE_ADMIN",
  BOARD_ADMIN = "BOARD_ADMIN",
  BOARD_MEMBER = "BOARD_MEMBER",
  SCHOOL_ADMIN = "SCHOOL_ADMIN",
  TEACHER = "TEACHER",
  STUDENT = "STUDENT",
  MENTOR = "MENTOR",
  INSTITUTION = "institution",
  EDUCATOR = "EDUCATOR",
  SCHOOL = "SCHOOL",
}

export enum PLAN_TARGET {
  STUDENT = "STUDENT",
  EDUCATOR = "EDUCATOR",
  SCHOOL = "SCHOOL",
  BOARD = "BOARD",
}

export enum BILLING_CYCLE {
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
}

export enum STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum PATENT_STATUS {
  PENDING = "PENDING",
  GRANTED = "GRANTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  REJECTED = "REJECTED",
}

export enum CATEGORY {
  RESEARCH = "RESEARCH",
  INNOVATION = "INNOVATION",
  ENTREPRENEURSHIP = "ENTREPRENEURSHIP",
}

export enum QUESTION_TYPE {
  TEXT = "TEXT",
  MCQ = "MCQ",
  BOOLEAN = "BOOLEAN",
}

export enum PLAN_BENEFITS {
  MAX_TEACHERS = "MAX_TEACHERS",
  MAX_STUDENTS = "MAX_STUDENTS",
  APPROVE_NOMINEE_TEACHERS = "APPROVE_NOMINEE_TEACHERS",
  MAX_INNOVATION_SUBMISSIONS = "MAX_INNOVATION_SUBMISSIONS",
  MAX_RESEARCH_SUBMISSIONS = "MAX_RESEARCH_SUBMISSIONS",
  MAX_SELF_NOMINATION_TEACHER = "MAX_SELF_NOMINATION_TEACHER",
}

export enum TRAINING_MODE {
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",
  HYBRID = "HYBRID",
  ANY_OF_THE_ABOVE = "ANY_OF_THE_ABOVE",
  IN_PERSON = "IN_PERSON",
}

export enum INNOVATION_STATUS {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  APPROVED_BY_ADMIN = "APPROVED_BY_ADMIN",
  REJECTED_BY_ADMIN = "REJECTED_BY_ADMIN",
  UNDER_REVIEW_BY_ATTORNEY = "UNDER_REVIEW_BY_ATTORNEY",
  APPROVED_BY_ATTORNEY = "APPROVED_BY_ATTORNEY",
  REJECTED_BY_ATTORNEY = "REJECTED_BY_ATTORNEY",
  PATENT_FILED_INDIA = "PATENT_FILED_INDIA",
  PATENT_FILED_USA = "PATENT_FILED_USA",
  PATENT_UNDER_PROSECUTION = "PATENT_UNDER_PROSECUTION",
  PATENT_GRANTED = "PATENT_GRANTED",
  PATENT_REJECTED = "PATENT_REJECTED",
  PATENT_PENDING = "PATENT_PENDING",
  REJECTED = "REJECTED",
  ARCHIVED = "ARCHIVED",
}

export enum FILE_TYPE {
  PPT = "PPT",
  VIDEOS = "VIDEO",
  PDF = "PDF",
  IMAGES = "IMAGE",
}

export enum RESOURCES_TYPE {
  CURRICULUM = "CURRICULUM",
  MODULES = "MODULE",
  DOCUMENT_TEMPLATE = "DOCUMENT",
  TRAINING_VIDEOS = "TRAINING_VIDEO",
  CASE_STUDIES = "CASE_STUDY",
  TEMPLATE = "TEMPLATE",
}

export enum TRAINING_NOMINATION_STATUS {
  SELF_NOMINATED = "SELF_NOMINATED",
  SCHOOL_APPROVED = "SCHOOL_APPROVED",
  INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
  INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",
  IAIRE_APPROVED = "IAIRE_APPROVED",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
  SCHOOL_ASSIGNED = "SCHOOL_ASSIGNED",

  TRAINING_COMPLETED = "TRAINING_COMPLETED",
}

export enum BATCH_STATUS {
  UPCOMING = "UPCOMING",
  ONGOING = "ONGOING",
  COMPLETED = "COMPLETED",
}

export enum RESEARCH_STATUS {
  PENDING = "PENDING",
  APPROVED_BY_ADMIN = "APPROVED_BY_ADMIN",
  FINAL_MANUSCRIPT_TO_PUBLICATION = "FINAL_MANUSCRIPT_TO_PUBLICATION",
  REJECTED_BY_ADMIN = "REJECTED_BY_ADMIN",
  PR_REVIEWED = "PR_REVIEWED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  PUBLISHED = "PUBLISHED",
  NOT_PUBLISHED = "NOT_PUBLISHED",
  ARCHIVED = "ARCHIVED",
}

export enum PRIORITY {
  HIGH = "HIGH",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
}

export enum SUPPORT_TICKET_STATUS {
  PENDING = "PENDING",
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "SOLVED",
  CLOSED = "CLOSED",
  REOPENED = "REOPENED",
}

export enum HEAD_NOMINATION_STATUS {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
}

export enum HONORARIUM_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  TRANSACTION_PENDING = "TRANSACTION_PENDING",
  PAID = "PAID",
  REJECTED = "REJECTED",
}

