export enum COLORS {
  WHITE = "#ffffff",
  BLACK = "#000000",
  PRIMARY_NAVY = "#09090B",
  ACCENT_TAN = "#A1A1AA",
  NAVY_GRADIENT_START = "#18181B",
  NAVY_GRADIENT_END = "#09090B",
  GLASS_BG = "rgba(255, 255, 255, 0.8)",
  GLASS_BORDER = "rgba(0, 0, 0, 0.08)",
  TEXT_PRIMARY = "#18181B",
  TEXT_SECONDARY = "#71717A",
  INPUT_BG = "#F4F4F5",
  BG_LIGHT = "#FAFAFA",
  BG_GRADIENT_END = "#E4E4E7",
  SUCCESS = "#10B981",
  ERROR = "#EF4444",
  WARNING = "#F59E0B",
  INFO = "#3B82F6",
  SECONDARY_NAVY = "#27272A",
  TRANSPARENT = "transparent",
}

export enum FONT_SIZE {
  FS28 = "28px",
  FS18 = "18px",
  FS16 = "16px",
  FS14 = "14px",
  FS12 = "12px",
}

export enum USER_ROLES {
  SUPER_ADMIN = "SUPER_ADMIN",
  IAIRE_ADMIN = "IAIRE_ADMIN",
  BOARD_ADMIN = "BOARD_ADMIN",
  BOARD_MEMBER = "BOARD_MEMBER",
  SCHOOL_ADMIN = "SCHOOL_ADMIN",
  TEACHER = "TEACHER",
  STUDENT = "STUDENT",
  MENTOR = "MENTOR",
  INSTITUTION = "institution",
  EDUCATOR = "EDUCATOR",
  SCHOOL = "SCHOOL",
}

export enum PLAN_TARGET {
  STUDENT = "STUDENT",
  EDUCATOR = "EDUCATOR",
  SCHOOL = "SCHOOL",
  BOARD = "BOARD",
}

export enum BILLING_CYCLE {
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
}

export enum STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum PATENT_STATUS {
  PENDING = "PENDING",
  GRANTED = "GRANTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  REJECTED = "REJECTED",
}

export enum CATEGORY {
  RESEARCH = "RESEARCH",
  INNOVATION = "INNOVATION",
  ENTREPRENEURSHIP = "ENTREPRENEURSHIP",
}

export enum QUESTION_TYPE {
  TEXT = "TEXT",
  MCQ = "MCQ",
  BOOLEAN = "BOOLEAN",
}

export enum PLAN_BENEFITS {
  MAX_TEACHERS = "MAX_TEACHERS",
  MAX_STUDENTS = "MAX_STUDENTS",
  APPROVE_NOMINEE_TEACHERS = "APPROVE_NOMINEE_TEACHERS",
  MAX_INNOVATION_SUBMISSIONS = "MAX_INNOVATION_SUBMISSIONS",
  MAX_RESEARCH_SUBMISSIONS = "MAX_RESEARCH_SUBMISSIONS",
  MAX_SELF_NOMINATION_TEACHER = "MAX_SELF_NOMINATION_TEACHER",
}

export enum TRAINING_MODE {
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",
  HYBRID = "HYBRID",
  ANY_OF_THE_ABOVE = "ANY_OF_THE_ABOVE",
  IN_PERSON = "IN_PERSON",
}

export enum INNOVATION_STATUS {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  PATENT_PENDING = "PATENT_PENDING",
  PATENT_GRANTED = "PATENT_GRANTED",
  REJECTED = "REJECTED",
  ARCHIVED = "ARCHIVED",
}

export enum FILE_TYPE {
  PPT = "PPT",
  VIDEOS = "VIDEO",
  PDF = "PDF",
  IMAGES = "IMAGE",
}

export enum RESOURCES_TYPE {
  CURRICULUM = "CURRICULUM",
  MODULES = "MODULE",
  DOCUMENT_TEMPLATE = "DOCUMENT",
  TRAINING_VIDEOS = "TRAINING_VIDEO",
  CASE_STUDIES = "CASE_STUDY",
  TEMPLATE = "TEMPLATE",
}

export enum TRAINING_NOMINATION_STATUS {
  SELF_NOMINATED = "SELF_NOMINATED",
  SCHOOL_APPROVED = "SCHOOL_APPROVED",
  INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
  INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",
  IAIRE_APPROVED = "IAIRE_APPROVED",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
}
