export enum COLORS {
  WHITE = "#ffffff",
  BLACK = "#000000",
  PRIMARY_NAVY = "#0B1727",
  ACCENT_TAN = "#D1A054",
  NAVY_GRADIENT_START = "#0B1727",
  NAVY_GRADIENT_END = "#16222F",
  GLASS_BG = "rgba(255, 255, 255, 0.7)",
  GLASS_BORDER = "rgba(255, 255, 255, 0.3)",
  TEXT_PRIMARY = "#1A1A1A",
  TEXT_SECONDARY = "#666666",
  INPUT_BG = "#F3F4F6",
  BG_LIGHT = "#f5f7fa",
  BG_GRADIENT_END = "#c3cfe2",
  SUCCESS = "#4CAF50",
  ERROR = "#F44336",
  WARNING = "#FF9800",
  INFO = "#2196F3",
  SECONDARY_NAVY = "#1C2B3E",
  TRANSPARENT = "transparent",
}

export enum FONT_SIZE {
  FS28 = "28px",
  FS18 = "18px",
  FS16 = "16px",
  FS14 = "14px",
  FS12 = "12px",
}

export enum USER_ROLES {
  SUPER_ADMIN = "SUPER_ADMIN",
  IAIRE_ADMIN = "IAIRE_ADMIN",
  BOARD_ADMIN = "BOARD_ADMIN",
  BOARD_MEMBER = "BOARD_MEMBER",
  SCHOOL_ADMIN = "SCHOOL_ADMIN",
  TEACHER = "TEACHER",
  STUDENT = "STUDENT",
  MENTOR = "MENTOR",
  INSTITUTION = "institution",
  EDUCATOR = "EDUCATOR",
  SCHOOL = "SCHOOL",
}

export enum PLAN_TARGET {
  STUDENT = "STUDENT",
  EDUCATOR = "EDUCATOR",
  SCHOOL = "SCHOOL",
  BOARD = "BOARD",
}

export enum BILLING_CYCLE {
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
}

export enum STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum PATENT_STATUS {
  PENDING = "PENDING",
  GRANTED = "GRANTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  REJECTED = "REJECTED",
}

export enum CATEGORY {
  RESEARCH = "RESEARCH",
  INNOVATION = "INNOVATION",
  ENTREPRENEURSHIP = "ENTREPRENEURSHIP",
}

export enum QUESTION_TYPE {
  TEXT = "TEXT",
  MCQ = "MCQ",
  BOOLEAN = "BOOLEAN",
}

export enum PLAN_BENEFITS {
  MAX_TEACHERS = "MAX_TEACHERS",
  MAX_STUDENTS = "MAX_STUDENTS",
  APPROVE_NOMINEE_TEACHERS = "APPROVE_NOMINEE_TEACHERS",
  MAX_INNOVATION_SUBMISSIONS = "MAX_INNOVATION_SUBMISSIONS",
  MAX_RESEARCH_SUBMISSIONS = "MAX_RESEARCH_SUBMISSIONS",
  MAX_SELF_NOMINATION_TEACHER = "MAX_SELF_NOMINATION_TEACHER",
}
